const getPersianStringNumber = (number: number) => {
    switch (number) {
        case 1:
            return 'اول';
        case 2:
            return 'دوم';
        case 3:
            return 'سوم';
        case 4:
            return 'چهارم';
        case 5:
            return 'پنجم';
        case 6:
            return 'ششم';
        case 7:
            return 'هفتم';
        case 8:
            return 'هشتم';
        case 9:
            return 'نهم';
        case 10:
            return 'دهم';
        case 11:
            return 'یازدهم';
        case 12:
            return 'دوازدهم';
        case 13:
            return 'سیزدهم';
        case 14:
            return 'چهاردهم';
        case 15:
            return 'پانزدهم';
        case 16:
            return 'شانزدهم';
        case 17:
            return 'هفدهم';
        case 18:
            return 'هجدهم';
        case 19:
            return 'نوزدهم';
        case 20:
            return 'بیستم';
        case 21:
            return 'بیست‌ویکم';
        case 22:
            return 'بیست‌ودوم';
        case 23:
            return 'بیست‌وسوم';
        case 24:
            return 'بیست‌وچهارم';
        case 25:
            return 'بیست‌وپنجم';
        case 26:
            return 'بیست‌وششم';
        case 27:
            return 'بیست‌وهفتم';
        case 28:
            return 'بیست‌وهشتم';
        case 29:
            return 'بیست‌ونهم';
        case 30:
            return 'سی‌ام';
        case 31:
            return 'سی‌ویکم';
        case 32:
            return 'سی‌ودوم';
        case 33:
            return 'سی‌وسوم';
        case 34:
            return 'سی‌وچهارم';
        case 35:
            return 'سی‌وپنجم';
        case 36:
            return 'سی‌وششم';
        case 37:
            return 'سی‌وهفتم';
        case 38:
            return 'سی‌وهشتم';
        case 39:
            return 'سی‌ونهم';
        case 40:
            return 'چهل‌ام';
        default:
            return number;
    }
};
export default getPersianStringNumber;
